package rs.sbnz.rules;

import rs.sbnz.gunorama.model.facts.GradjaninZdravstvenoSposobanFact;
import rs.sbnz.gunorama.model.Zahtjev;
import rs.sbnz.gunorama.model.faze.ZdravstvenoSposobanFaza;


rule "Gradjanin Zdravstveno Sposoban - prosao evaluaciju"
	agenda-group "Zdravstvena evaluacija"
    no-loop true
    when
        $z: Zahtjev($id: id) and
        $zsf: ZdravstvenoSposobanFaza(zahtjevId == $id, dioptrija >= -1.0, dioptrija <= 1.0, prosaoPsiholoskuEvaluaciju == true, prosaoPsihijatrijskuEvaluaciju == true)
    then
    	System.out.println("GRADJANIN PROLAZI EVALUACIJU ");
    	insert(new GradjaninZdravstvenoSposobanFact($id, true));
end


rule "Gradjanin Zdravstveno Sposoban - pao evaluaciju"
	agenda-group "Zdravstvena evaluacija"
	no-loop true
    when
        $z: Zahtjev($id: id) and (
        $zsf: ZdravstvenoSposobanFaza(zahtjevId == $id, dioptrija < -1.0) or
        $zsf: ZdravstvenoSposobanFaza(zahtjevId == $id, dioptrija > 1.0) or
        $zsf: ZdravstvenoSposobanFaza(zahtjevId == $id, prosaoPsiholoskuEvaluaciju == false) or
        $zsf: ZdravstvenoSposobanFaza(zahtjevId == $id, prosaoPsihijatrijskuEvaluaciju == false)
        )
    then
    	System.out.println("GRADJANIN PADA EVALUACIJU");
        modify($z) {
            setRazlogOdbijanja("Gradjanin nije zdravstveno sposoban.");
        }
    	insert(new GradjaninZdravstvenoSposobanFact($id, false));
end
