package rs.sbnz.gunorama.model.enums;

public enum Dokument {
    LICNA_KARTA,
    DOKAZ_O_CLANSTVU_U_STRELJACKOM_KLUBU,
    DOKAZ_O_POLOZENOM_LOVACKOM_ISPITU,
    DOKAZ_O_CLANSTVU_U_LOVACKOM_DRUSTVU,
    DOKAZ_O_CLANSTVU_U_LOVACKO_STRELJACKOM_DRUSTVU,
    DOKAZ_O_UGROZENOSTI_LICNE_BEZJEDNOSTI,
    DOKAZ_O_POLOZENOJ_OBUCI_ZA_RUKOVANJE_ORUZJEM,
    DOKAZ_O_NEOSUDJIVANOSTI_ZA_NASILNA_KRIVICNA_DJELA,
    DOKAZ_O_UPLACENIM_NEOPHODNIM_TAKSAMA,
    DOKAZ_O_PLACENOJ_CLANARINI_U_LOVACKOM_ILI_STRELJACKOM_KLUBU

}
