package rs.sbnz.gunorama.model.enums;

public enum KonkretnaNamjena {
    LOV_SITNE_DIVLJACI, LOV_KRUPNE_DIVLJACI, //LOV
    SKIT, TRAP, //LOVNO_STRELJASTVO
    KRATKOMETNO_GADJANJE, DALEKOMETNO_GADJANJE, //STRELJASTVO
    NOSENJE, POSJEDOVANJE //SAMOODBRANA
}
